# Settings
url: "https://lufevida.github.io"
baseurl: "/html5up-stellar"
markdown: kramdown
title: "Stellar by HTML5 UP"
tagline: "Just another free, fully responsive site template built by @ajlkn for HTML5 UP."
#copyright: Copyright Owner
#email: your-email@domain.com
#phone: 012-345-6789
#twitter: username
#facebook: username
#instagram: username
#dribbble: username
#github: username
#500px: username