# Site settings
title: "Stellar by HTML5 UP"
email: your-email@domain.com
phone: 012-345-6789
copyright: Copyright Owner
tagline: "Just another free, fully responsive site template<br />built by <a href="https://twitter.com/ajlkn">@ajlkn</a> for <a href="https://html5up.net">HTML5 UP</a>."
baseurl: "/html5up-stellar" # the subpath of your site, e.g. /blog
url: "https://lufevida.github.io" # the base hostname & protocol for your site
twitter: username
facebook: username
instagram: username
dribbble: username
github: username
500px: username

# Build settings
markdown: kramdown