# General Settings
url: "https://lufevida.github.io"
baseurl: "/html5up-stellar"
markdown: kramdown
title: "Stellar"
tagline: "Just another free, fully responsive site template built by @ajlkn for HTML5 UP."
footerTitle: Aliquam sed mauris
footerText: Sed lorem ipsum dolor sit amet et nullam consequat feugiat consequat magna adipiscing tempus etiam dolore veroeros. eget dapibus mauris. Cras aliquet, nisl ut viverra sollicitudin, ligula erat egestas velit, vitae tincidunt odio.
footerButtonTitle: Learn More
footerButtonLink: pages/elements.html
copyright: Copyright Owner

# Contact Settings
contactTitle: Etiam feugiat
address: 1234 Somewhere Road &bull; Nashville, TN 00000 &bull; USA
email: your-email@domain.com
phone: 012-345-6789
twitter: username
facebook: username
instagram: username
dribbble: username
github: username